/**
 * Generates the opencode bridge plugin — the plugin file opencode's Bun
 * runtime loads from `<serverCwd>/.opencode/plugins/*.ts` (spike.md §1). At
 * startup it `fetch`es the bridge's `GET /tools` manifest and registers one
 * opencode custom tool per entry; each tool's `execute` forwards the call to
 * the bridge's `POST /tool` endpoint, carrying the opencode session id
 * (`ctx.sessionID` — spike.md §2, the second arg of `execute(args, ctx)`) so
 * the bridge can resolve the calling Task/Agent via its SessionRegistry.
 *
 * The bridge URL + bearer token are baked as literals into the generated
 * source (via `JSON.stringify`, never `process.env`) because both are known
 * in the Archie process at boot, when the bridge listener is started — this
 * sidesteps any question of whether env vars are forwarded into the
 * `opencode serve` child process (spike.md §6, Plan impact).
 *
 * Security: the generated file embeds the bearer token in plaintext on disk,
 * so `pluginsDir`'s ancestor (`.opencode/`) MUST stay out of version control
 * (see `.gitignore`). This module itself never logs the token — it only
 * writes it into the generated file.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { RO_BUILTIN_BLOCK } from './server.js';

const PLUGIN_FILENAME = 'archie-bridge.ts';

/**
 * Render the opencode plugin module source. `bridgeUrl`/`token` are baked in
 * as literals (no `process.env` reads) — see module doc.
 */
export function renderBridgePlugin(bridgeUrl: string, token: string): string {
  return `// AUTO-GENERATED by Archie (src/runtime/opencode/bridge/plugin-source.ts).
// Do not edit by hand — regenerated on every boot. Contains a live bearer
// token: never commit this file (see .opencode/ in .gitignore).
import { tool } from "@opencode-ai/plugin";

const BRIDGE_URL = ${JSON.stringify(bridgeUrl)};
const BRIDGE_TOKEN = ${JSON.stringify(token)};
// Fail-closed default: baked from the bridge's own RO_BUILTIN_BLOCK so the
// generated plugin blocks these built-ins whenever /policy can't be
// authoritatively resolved (bridge unreachable, non-2xx, or malformed body).
const FAIL_CLOSED_BLOCKED_TOOLS = ${JSON.stringify(RO_BUILTIN_BLOCK)};

function schemaFor(spec) {
  let base;
  switch (spec.type) {
    case "string":
      base = tool.schema.string();
      break;
    case "number":
      base = tool.schema.number();
      break;
    case "boolean":
      base = tool.schema.boolean();
      break;
    case "object":
    default:
      base = tool.schema.any();
      break;
  }
  return spec.optional ? base.optional() : base;
}

export const ArchieBridgePlugin = async (pluginCtx) => {
  const manifestRes = await fetch(BRIDGE_URL + "/tools", {
    headers: { authorization: "Bearer " + BRIDGE_TOKEN },
  });
  const manifest = await manifestRes.json();

  const tools = {};
  for (const entry of manifest) {
    const argsSchema = entry.argsSchema || {};
    const args = {};
    for (const argName of Object.keys(argsSchema)) {
      args[argName] = schemaFor(argsSchema[argName]);
    }
    tools[entry.name] = tool({
      description: entry.description,
      args,
      async execute(toolArgs, ctx) {
        const r = await fetch(BRIDGE_URL + "/tool", {
          method: "POST",
          headers: {
            "content-type": "application/json",
            authorization: "Bearer " + BRIDGE_TOKEN,
          },
          body: JSON.stringify({ sessionId: ctx.sessionID, tool: entry.name, args: toolArgs }),
        });
        const j = await r.json();
        if (!j.ok) throw new Error(j.error);
        return j.result;
      },
    });
  }

  // RO guard (B.2 spike-proven mechanism, see __spike__/b2-spike.md): opencode's
  // built-in edit/write/bash tools have no per-session permission surface, so
  // the shared server-wide config.permission can't gate them per session. A
  // plugin "tool.execute.before" hook that throws for a session's blocked
  // tools is the only mechanism the spike found that actually blocks them.
  // The guard resolves each session's policy via the bridge's bearer-gated
  // GET /policy?sessionId=<id>, caching the result per sessionID in this
  // module-level Map so a long-running session pays the round-trip once, not
  // on every tool call.
  const policyCache = new Map();

  // Fail-closed choice: any time the policy cannot be AUTHORITATIVELY
  // resolved — the fetch throws, the response isn't 2xx, or the body is
  // missing/malformed — we return the baked FAIL_CLOSED_BLOCKED_TOOLS
  // default rather than an empty allow-list. Built-in edit/write/bash/etc.
  // are the only thing this guard protects (they run in the opencode child
  // and never touch the bridge's own /tool dispatch backstop), so failing
  // open here would be a full read-only bypass. Read built-ins are never in
  // that set, so they stay usable even while failing closed. Only a
  // well-formed 2xx response is cached — a transient failure must retry on
  // the next call instead of pinning the session unguarded (or over-blocked)
  // for its remaining lifetime.
  async function resolvePolicy(sessionID) {
    if (policyCache.has(sessionID)) return policyCache.get(sessionID);
    let r;
    try {
      r = await fetch(BRIDGE_URL + "/policy?sessionId=" + encodeURIComponent(sessionID), {
        headers: { authorization: "Bearer " + BRIDGE_TOKEN },
      });
    } catch {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    if (!r.ok) {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    let j;
    try {
      j = await r.json();
    } catch {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    if (!j || !Array.isArray(j.blockedTools)) {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    const policy = { blockedTools: j.blockedTools };
    policyCache.set(sessionID, policy);
    return policy;
  }

  return {
    tool: tools,
    "tool.execute.before": async (input, output) => {
      const policy = await resolvePolicy(input.sessionID);
      if (policy.blockedTools.includes(input.tool)) {
        throw new Error("read-only mode: " + input.tool + " not permitted");
      }
    },
  };
};
`;
}

/**
 * Write the rendered plugin into `pluginsDir` (created if missing) and
 * return the file's path.
 */
export async function writeBridgePlugin(pluginsDir: string, bridgeUrl: string, token: string): Promise<string> {
  await mkdir(pluginsDir, { recursive: true });
  const path = join(pluginsDir, PLUGIN_FILENAME);
  await writeFile(path, renderBridgePlugin(bridgeUrl, token), 'utf8');
  return path;
}
