/**
 * Generates the opencode bridge plugin — the plugin file opencode's Bun
 * runtime loads from `<serverCwd>/.opencode/plugins/*.ts`. At
 * startup it `fetch`es the bridge's `GET /tools` manifest and registers one
 * opencode custom tool per entry; each tool's `execute` forwards the call to
 * the bridge's `POST /tool` endpoint, carrying the opencode session id
 * (`ctx.sessionID`, the second arg of `execute(args, ctx)`) so
 * the bridge can resolve the calling Task/Agent via its SessionRegistry.
 *
 * The bridge URL + bearer token are baked as literals into the generated
 * source (via `JSON.stringify`, never `process.env`) because both are known
 * in the Archie process at boot, when the bridge listener is started — this
 * sidesteps any question of whether env vars are forwarded into the
 * `opencode serve` child process.
 *
 * Security: the generated file embeds the bearer token in plaintext on disk,
 * so `pluginsDir`'s ancestor (`.opencode/`) MUST stay out of version control
 * (see `.gitignore`). This module itself never logs the token — it only
 * writes it into the generated file.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { RO_BUILTIN_BLOCK } from './server.js';

const PLUGIN_FILENAME = 'archie-bridge.ts';

/**
 * Render the opencode plugin module source. `bridgeUrl`/`token` are baked in
 * as literals (no `process.env` reads) — see module doc.
 */
export function renderBridgePlugin(bridgeUrl: string, token: string): string {
  return `// AUTO-GENERATED by Archie (src/runtime/opencode/bridge/plugin-source.ts).
// Do not edit by hand — regenerated on every boot. Contains a live bearer
// token: never commit this file (see .opencode/ in .gitignore).
import { tool } from "@opencode-ai/plugin";

const BRIDGE_URL = ${JSON.stringify(bridgeUrl)};
const BRIDGE_TOKEN = ${JSON.stringify(token)};
// Fail-closed default: baked from the bridge's own RO_BUILTIN_BLOCK so the
// generated plugin blocks these built-ins whenever /policy can't be
// authoritatively resolved (bridge unreachable, non-2xx, or malformed body).
const FAIL_CLOSED_BLOCKED_TOOLS = ${JSON.stringify(RO_BUILTIN_BLOCK)};

// Rebuild a zod schema from the bridge's recursive ArgSpec (see server.ts).
// Nested objects/arrays + descriptions + enums are reconstructed faithfully so
// the opencode model gets the same arg guidance the Claude SDK path gives it —
// a structured arg (e.g. spawn_repo_agent's repos: [{github,...}]) is NOT
// flattened to any(), which would make the model guess the shape wrong.
function schemaFor(spec) {
  let base;
  switch (spec.type) {
    case "string":
      base = (spec.enum && spec.enum.length) ? tool.schema.enum(spec.enum) : tool.schema.string();
      break;
    case "number":
      base = tool.schema.number();
      break;
    case "boolean":
      base = tool.schema.boolean();
      break;
    case "array":
      base = tool.schema.array(spec.items ? schemaFor(spec.items) : tool.schema.any());
      break;
    case "object":
      if (spec.properties) {
        const shape = {};
        for (const key of Object.keys(spec.properties)) shape[key] = schemaFor(spec.properties[key]);
        base = tool.schema.object(shape);
      } else {
        base = tool.schema.any();
      }
      break;
    default:
      base = tool.schema.any();
      break;
  }
  if (spec.description) base = base.describe(spec.description);
  return spec.optional ? base.optional() : base;
}

export const ArchieBridgePlugin = async (pluginCtx) => {
  const manifestRes = await fetch(BRIDGE_URL + "/tools", {
    headers: { authorization: "Bearer " + BRIDGE_TOKEN },
  });
  const manifest = await manifestRes.json();

  const tools = {};
  for (const entry of manifest) {
    const argsSchema = entry.argsSchema || {};
    const args = {};
    for (const argName of Object.keys(argsSchema)) {
      args[argName] = schemaFor(argsSchema[argName]);
    }
    tools[entry.name] = tool({
      description: entry.description,
      args,
      async execute(toolArgs, ctx) {
        const r = await fetch(BRIDGE_URL + "/tool", {
          method: "POST",
          headers: {
            "content-type": "application/json",
            authorization: "Bearer " + BRIDGE_TOKEN,
          },
          body: JSON.stringify({ sessionId: ctx.sessionID, tool: entry.name, args: toolArgs }),
        });
        const j = await r.json();
        if (!j.ok) throw new Error(j.error);
        return j.result;
      },
    });
  }

  // RO guard: opencode's built-in edit/write/bash tools have no per-session
  // permission surface, so
  // the shared server-wide config.permission can't gate them per session. A
  // plugin "tool.execute.before" hook that throws for a session's blocked
  // tools is the only mechanism that actually blocks them.
  // The guard resolves each session's policy via the bridge's bearer-gated
  // GET /policy?sessionId=<id> on EVERY tool.execute.before call — no
  // per-session caching. A session's policy can change mid-session: the
  // edit-mode approval flow re-spawns a repo agent RESUMING THE SAME
  // opencode sessionID with readOnly flipped RO -> edit in the bridge's
  // SessionRegistry, and the guard must observe that flip on the very next
  // tool call rather than replaying a stale decision for the rest of the
  // session's lifetime. The round-trip is a loopback fetch to the bridge
  // (same host), so paying it on every call is negligible.
  //
  // Fail-closed choice: any time the policy cannot be AUTHORITATIVELY
  // resolved — the fetch throws, the response isn't 2xx, or the body is
  // missing/malformed — we return the baked FAIL_CLOSED_BLOCKED_TOOLS
  // default rather than an empty allow-list. Built-in edit/write/bash/etc.
  // are the only thing this guard protects (they run in the opencode child
  // and never touch the bridge's own /tool dispatch backstop), so failing
  // open here would be a full read-only bypass. Read built-ins are never in
  // that set, so they stay usable even while failing closed.
  async function resolvePolicy(sessionID) {
    let r;
    try {
      r = await fetch(BRIDGE_URL + "/policy?sessionId=" + encodeURIComponent(sessionID), {
        headers: { authorization: "Bearer " + BRIDGE_TOKEN },
      });
    } catch {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    if (!r.ok) {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    let j;
    try {
      j = await r.json();
    } catch {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    if (!j || !Array.isArray(j.blockedTools)) {
      return { blockedTools: FAIL_CLOSED_BLOCKED_TOOLS };
    }
    return { blockedTools: j.blockedTools };
  }

  return {
    tool: tools,
    "tool.execute.before": async (input, output) => {
      const policy = await resolvePolicy(input.sessionID);
      if (policy.blockedTools.includes(input.tool)) {
        throw new Error("read-only mode: " + input.tool + " not permitted");
      }
    },
  };
};
`;
}

/**
 * Write the rendered plugin into `pluginsDir` (created if missing) and
 * return the file's path.
 */
export async function writeBridgePlugin(pluginsDir: string, bridgeUrl: string, token: string): Promise<string> {
  await mkdir(pluginsDir, { recursive: true });
  const path = join(pluginsDir, PLUGIN_FILENAME);
  await writeFile(path, renderBridgePlugin(bridgeUrl, token), 'utf8');
  return path;
}
