import { writeFile, chmod, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

/** Build the trailer lines Archie stamps on every commit: the bot as
 * co-author (folded here so opencode commits get it too) and the requesting
 * human. The commit author is set separately (the edit-mode approver). */
export function buildCommitTrailers(
  bot: { name: string; email: string } | null,
  requester: { id: string; name: string; source: string } | undefined,
): string[] {
  const lines: string[] = [];
  if (bot) lines.push(`Co-Authored-By: ${oneLine(bot.name)} <${oneLine(bot.email)}>`);
  if (requester) {
    lines.push(
      requester.source === 'cli'
        ? 'Requested-by: cli'
        : `Requested-by: ${oneLine(requester.name)} (@${oneLine(requester.id)})`,
    );
  }
  return lines;
}

/** Collapse any control chars (newlines, tabs, …) to single spaces: a git
 * trailer is one line, and the hook's `grep -qxF` idempotency check matches
 * whole lines, so an embedded newline in an (externally-sourced) name would
 * defeat de-duplication and re-append the trailer on every amend/rebase. */
function oneLine(s: string): string {
  return s.replace(/\p{Cc}+/gu, ' ').trim();
}

/** A `prepare-commit-msg` hook that appends each trailer once (idempotent) and
 * never fails a commit. Values are baked in — no env plumbing through the
 * opencode sandbox. Fires on every `git commit` (not skipped by --no-verify). */
export function renderPrepareCommitMsgHook(trailers: string[]): string {
  const adds = trailers
    .map((t) => `grep -qxF ${shq(t)} "$F" 2>/dev/null || printf '%s\\n' ${shq(t)} >> "$F"`)
    .join('\n');
  return `#!/bin/sh\n# Auto-generated by Archie — SOC2 commit attribution trailers.\nF="$1"\n[ -n "$F" ] || exit 0\n${adds}\nexit 0\n`;
}

/** Single-quote a string for POSIX sh. */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export async function writeCommitTrailerHook(clonePath: string, trailers: string[]): Promise<void> {
  if (trailers.length === 0) return;
  const hooksDir = join(clonePath, '.git', 'hooks');
  await mkdir(hooksDir, { recursive: true });
  const hookPath = join(hooksDir, 'prepare-commit-msg');
  await writeFile(hookPath, renderPrepareCommitMsgHook(trailers), 'utf-8');
  await chmod(hookPath, 0o755);
}
